export enum Region {
  NORTH = 'NORTH',
  SOUTH = 'SOUTH',
  EAST = 'EAST',
  WEST = 'WEST'
}

export enum MetricType {
  SIGNUPS = 'SIGNUPS',
  MARKETING_BANNERS = 'MARKETING_BANNERS',
  DIGITAL_MARKETING_VIEWS = 'DIGITAL_MARKETING_VIEWS',
  CUSTOMER_SURVEYS = 'CUSTOMER_SURVEYS',
  KEYNOTE_SPEAKING = 'KEYNOTE_SPEAKING',
  ENGAGEMENT_ACTIVITY = 'ENGAGEMENT_ACTIVITY',
  ANNOUNCEMENTS = 'ANNOUNCEMENTS',
  LOGO_ON_POSTERS = 'LOGO_ON_POSTERS'
}

export enum FeatureType {
  STALLS = 'STALLS',
  TITLE_RIGHTS = 'TITLE_RIGHTS',
  MAIN_STAGE_BACKDROP = 'MAIN_STAGE_BACKDROP',
  STANDEES = 'STANDEES',
  OTHER = 'OTHER'
}

export enum CampaignPlan {
  QUARTERLY = 'QUARTERLY',
  HALF_YEARLY = 'HALF_YEARLY',
  YEARLY = 'YEARLY'
}